version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
