packages:
  - 'backend'
  - 'shared'
  - 'dashboard'

minimumReleaseAge: 20160 # in minutes (2 weeks)
minimumReleaseAgeExclude:
  - 'knub'
  - 'knub-command-manager'

overrides:
  # Keep in sync with Knub's discord.js version
  discord.js: "14.19.3"
  discord-api-types: "0.38.1"
