packages:
  - 'backend'
  - 'shared'
  - 'dashboard'

minimumReleaseAge: 20160 # in minutes (2 weeks)
minimumReleaseAgeExclude:
  - 'vety'
  - 'knub-command-manager'

overrides:
  # Keep in sync with Vety's discord.js version
  discord.js: "14.23.2"
  discord-api-types: "0.38.30"
